name: Awesome ChatGPT Prompts
title: null

# Dark mode configuration
dark_mode: true

# GitHub Pages configuration
github_pages:
  url: "https://<your-github-username>.github.io/<your-repo-name>"
  branch: "gh-pages"
