
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// `prisma generate` is pure client codegen and never opens a connection, but
// prisma/config's env() helper throws at config-load time when DATABASE_URL is
// unset — which breaks codegen in environments that legitimately don't carry
// the secret (e.g. Vercel Preview builds, where postinstall runs generate).
// Read the variable directly and fall back to a non-functional placeholder so
// generate works without a database. Every command that actually connects
// (migrate, db push, seed) and all runtime code run only where DATABASE_URL is
// set, so the placeholder is never dialed.
const databaseUrl =
  process.env.DATABASE_URL ??
  "postgresql://placeholder:placeholder@localhost:5432/placeholder";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: databaseUrl,
  },
});
