name: Feature Request
description: Suggest an idea for this project
title: '[Feature]: '
labels: ['enhancement', 'triage']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for sharing your ideas to improve prompts.chat!
  - type: textarea
    id: problem
    attributes:
      label: The Problem
      description: Is your feature request related to a problem? Please describe.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: The Solution
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false
