name: 🚀 New Prompt Submission
description: Suggest a new ChatGPT prompt for the collection.
title: "[PROMPT]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: prompt_text
    attributes:
      label: Prompt Content
      description: Provide the full text of the prompt.
      placeholder: "I want you to act as..."
    validations:
      required: true
  - type: input
    id: category
    attributes:
      label: Category
      placeholder: "e.g., Coding, Writing, Linux Terminal"
    validations:
      required: true